### ISSUE TITLE
Convert hashing from MD5 -> Bcrypt

### ISSUE THREAD

**Issue by anderslatif** [MinitwitGroupI/MiniTwit#58]
Lot's of articles online on why we shouldn't use md5. 
https://stackoverflow.com/questions/30496061/why-not-use-md5-for-password-hashing

My suggestion:
https://pypi.org/project/bcrypt/

We will also do penetration testing one of the coming weeks.

**Comment by Metallist1** [comment]
Do note, a lot of passwords are already crypted to MD5. Thus there is a need to create a migration system.
We dont know the passwords content by design, so we might want to check if its crypted to MD5 and change it to Bcrypt.

**Comment by anderslatif** [comment]
We have moved away from using md5 but users still remain in the db with insecure md5 hashes.

To solve this issue I went with Nedas' trick to stealthily change legacy users' passwords with better encryption as they login. But I'm keeping the things below for posterity to write out the design choice that was made.

The options are:

* Option 1 is to remove all data. It's a quick fix but then we lose "real users". 

* Option 2 is the professional choice of asking flagged users to reset password. 
This requires:
- Creating a new HTML page for forcing users to change their password.  
- Creating a new router.
- Littering all layers of our beautiful code base:
1. In auth_service that checks if the hashed password is not of type bcrypt. 
2. In our router that checks if the return value from the auth_service means that they are a legacy user. 

* Option 3 is Nedas' ingenious hack of just overwriting their previous password with bcrypt encrypted. We can do this since we receive the password in plaintext. 

I initially started implementing Option 2 but I decided on Option 3 in the end. 

Reason 1: Security
Simplicity is to be preferred when it comes to security. 
Option 2 opened up for many edge cases. 

Reason 2: DevOPs opinion on the matter
In a real-life scenario option 2 would be the nicest feature since we could reuse the reset password feature. 
But I ended up adhering to the spirit of the course: anything that does not provide value to customers or DX is not worth fussing about.

**Comment by anderslatif** [comment]
Can be closed once this is merged:
https://github.com/MinitwitGroupI/MiniTwit/pull/65

**Comment by anderslatif** [comment]
I forgot to mention Option 4 which is to comb through the md5 passwords existing in our database and convert them. 
This can be done by simply looking up their corresponding value in rainbow table and convert that to Bcrypt. 
This was an idea I only briefly entertained simply because we don't have setup database data migrations yet.

**Comment by Metallist1** [comment]
Fixed up errors. This issue is now resolved.
