### ISSUE TITLE
FastAPI Refactor: Auth router

### ISSUE THREAD

**Issue by anderslatif** [MinitwitGroupI/MiniTwit#8]

**Comment by anderslatif** [comment]
It's this file:
https://github.com/MinitwitGroupI/MiniTwit/blob/main/refactor_fastapi/routers/auth.py

Handle form validation:
https://fastapi.tiangolo.com/tutorial/request-forms/

Feel free to setup session or mark it as a todo.

**Comment by var-i** [comment]
https://github.com/MinitwitGroupI/MiniTwit/pull/16
